title: Nicholas A. Porter
description: I like to teach science and tinker in wood and code. | 505.750.8362 | nick@porternick.com
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
